package(default_visibility = ["//visibility:public"])
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "cmn_logging",
    srcs = ["cmn_logging.py"],
)

py_library(
    name = "calc_simresults_location",
    srcs = ["calc_simresults_location.py"],
)
