package(default_visibility = ["//visibility:public"])

exports_files([
    "xrun_compile_args_template.txt",
    "xrun_runtime_args_template.txt",
    "dv_unit_test_sim_template.sh",
    "rtl_unit_test_sim_template.sh",
    "rtl_svunit_test_template.sh",
])
