name: bazel-tests
on: [push]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: install-bazelisk
      uses: vsco/bazelisk-action@v1.0.0
      with:
        version: '1.7.5'
        bazel-install-path: './.local/bin'
        os: 'linux'

    - name: run-buildifier-diff
      run: bazel run //tests:buildifier_format_diff
